module.exports = {
  newQueue: `INSERT INTO CONTROLE_DE_PROCESSOS (ID, STATUS, TOTAL_ITENS, PROCESSOREFERENTE,TIPO) VALUES (?, 'INICIADA', ?, ?, ?);`,

  updateQueue: `UPDATE CONTROLE_DE_PROCESSOS SET STATUS = 'PROCESSANDO', QNT_PROCESSADA = ? WHERE ID = ?;`,

  finalizeQueue: `UPDATE CONTROLE_DE_PROCESSOS SET STATUS='FINALIZADO' WHERE ID = ?;`,
};
