module.exports = {
  updateQueue: `UPDATE CONTROLE_DE_PROCESSOS SET STATUS = 'PROCESSANDO', QNT_PROCESSADA = ? WHERE ID = ?;`,

  finalizeQueue: `UPDATE CONTROLE_DE_PROCESSOS SET STATUS='FINALIZADO' WHERE ID = ?;`,
};
